### ISSUE TITLE
The control service configuration information is required twice

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/unofficial-flocker-tools#3]
In cluster.yml, `/control_node` and `/agent_config/control-service/hostname` have the same value. Users shouldn't be expected to enter the same information twice.

**Comment by lukemarsden** [comment]
Thanks for the feedback! If you feel so inclined, please can you propose a PR which subs `/control_node` into `/agent_config/control-service/hostname` in the code before pushing `agent.yml` to the nodes?

**Comment by robhaswell** [comment]
Your suggestion seems to conflict with the desire to pass the control service configuration through unmodified (https://github.com/lukemarsden/unofficial-flocker-tools/issues/4#issuecomment-107458906). If you want to keep that behaviour, then `/control_node` should be removed and the value taken from the agent config.

**Comment by lukemarsden** [comment]
I don't want to silently rewrite the keys (and the issue in #4 is that the _Flocker_ agent config uses inconsistent hyphens and underscores, so if you want to fix that you should raise a Flocker JIRA) but I think I'm OK with substituting values into the config to make it easier for users.

**Comment by lukemarsden** [comment]
fixed in terraform installer
