### ISSUE TITLE
Plugin installer should install official plugin, not labs one

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/unofficial-flocker-tools#32]

**Comment by itamarst** [comment]
Once this is done you'll want to restore relevant section in Labs flocker docs; I am deleting ucrrent instructions since they will install wrong version of plugin.

**Comment by lukemarsden** [comment]
Thanks, which Flocker release included first installable & working flongle?

**Comment by lukemarsden** [comment]
fixed
