### ISSUE TITLE
uft-flocker-sample-files step is unneccessary

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/unofficial-flocker-tools#35]
Running `uft-flocker-sample-files` seems redundant. It doesn't do anything which allows me to interject or alter the course of the installation, it's just an extra step to run.

It should be combined with `uft-flocker-get-nodes`, possibly into a step called `uft-flocker-provision`.

**Comment by lukemarsden** [comment]
There are some user flows where you'd want to run uft-flocker-sample-files without uft-flocker-get-nodes (installing on managed nodes, for example). Those flows aren't documented yet, but I'd like to keep the separation so that it's easier to support them if/when we do.
