### ISSUE TITLE
cluster.yml mixes underscores and hyphens

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/unofficial-flocker-tools#4]
The key format for cluster.yml mixes underscores and hyphens. This is confusing for users, who must remember when to use one format and when to use another.

**Comment by lukemarsden** [comment]
The `agent_config` section gets passed unmodified into `/etc/flocker/agent.yml` on the nodes, so we can't change any keys under that. Is this inconsistency one of them?

**Comment by robhaswell** [comment]
Yeah, that's where the inconsistency is and the way that it is passed through unmodified is the cause of that.

**Comment by lukemarsden** [comment]
Closing this as I'd rather opaquely pass through this data rather than massaging it for style reasons. Thanks!
